### ISSUE TITLE
Code examples link to code using react, not Vue

### ISSUE THREAD

**Issue by bradsiefert** [ConvertKit/convertkit-vue#1]
I'm struggling to get this plugin running and it would help to be able to see a code examples. The two links you have:  "how to use different templates here" and "how to style your form with custom styling here" both link to examples using React instead of VueJs. 

If you could create code sandboxes for VueJs it would really help me out. I'm a noob and don't really understand the exact differences between the two.

**Comment by josephrexme** [comment]
Hi @bradsiefert I'm sorry for the confusion. The vue version is still in development and not ready yet. I will update yet when we have a working version. The codesandbox links will also be updated. The changes should happen some time next week.

**Comment by bradsiefert** [comment]
Thank you @josephrexme! I ended up setting up Mailchimp, for my site, but I'll look into trying ConvertKit once you've got it up and running.

**Comment by josephrexme** [comment]
Hi @bradsiefert here is an update for you that the plugin should work for both Vue 2 and Vue 3 now. You can see Vue 3 demos [here](https://codesandbox.io/s/cranky-stallman-ejvwp) and Vue 2 demos [here](https://codesandbox.io/s/xenodochial-wiles-k8kk9) . The README has also been updated to show how to install for whichever version you use.
